<?php

/**
 * Implements hook_block_info().
 */
function hbc_gmaps_block_info() {

  $blocks['gmaps'] = array(
    'info' => t('HBC Gmaps Block'),
//    'region' => 'content',
//    'status' => TRUE,
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hbc_gmaps_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'gmaps':
      $block['subject'] = '';
      $block['content'] = array(
        '#theme' => 'hbc_gmaps',
        '#url' => 'rss.xml',
        '#title' => t('Syndicate'),
      );
      break;
  }
  return $block;
}

function hbc_gmaps_theme($existing, $type, $theme, $path) {
  return array(
    'hbc_gmaps' => array(
      'template' => 'templates/hbc_gmaps',
      'variables' => array(
        'var_name'=> NULL
      )
    ),
  );
}


/**
 * Implements hook_preprocess_HOOK().
 */
function hbc_gmaps_preprocess_page(&$variables) {
  $node = $variables['node'];
  if($node->type == 'page' && $node->nid == 6) {
    $modulePath = drupal_get_path('module', 'hbc_gmaps');
    drupal_add_js('https://maps.googleapis.com/maps/api/js?key=AIzaSyCxPMFKItqPYezCGKYcvFl3reOl70tO1jM', 'external');
    drupal_add_js(array('hbc_gmaps' => array('pathx' => $modulePath)), 'setting');
    drupal_add_js(drupal_get_path('module', 'hbc_gmaps') . '/js/hbc_gmaps.js', 'file');
  }
}